# Generated by Django 5.1.4 on 2026-04-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingjob',
            name='minimum_plan_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
