# Generated by Django 5.1.4 on 2026-04-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_alter_writingjob_minimum_plan_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingjob',
            name='payment_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='writingjob',
            name='payment_transaction_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='writingjob',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='writing_submissions/'),
        ),
        migrations.AddField(
            model_name='writingjobhistory',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='writingjobhistory',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
