# Generated by Django 5.1.4 on 2026-04-19 05:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcript_text', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('admin_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'transcription_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('ADMIN', 'Admin Upload'), ('LIBRIVOX', 'LibriVox API')], default='LIBRIVOX', max_length=20)),
                ('difficulty', models.CharField(choices=[('BASIC', 'Basic'), ('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='BASIC', max_length=10)),
                ('language', models.CharField(default='English', max_length=50)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('pay_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_plan_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8')], default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=15)),
                ('librivox_id', models.CharField(blank=True, max_length=50)),
                ('librivox_section_id', models.CharField(blank=True, max_length=50)),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('book_title', models.CharField(blank=True, max_length=200)),
                ('book_author', models.CharField(blank=True, max_length=200)),
                ('audio_filename', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transcription_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
