# Generated by Django 5.1.4 on 2026-04-19 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcriptionsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcriptiontask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transcription_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcriptionsubmission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='transcription.transcriptiontask'),
        ),
        migrations.AlterUniqueTogether(
            name='transcriptionsubmission',
            unique_together={('task', 'user')},
        ),
    ]
