# Generated by Django 5.1.4 on 2026-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptiontask',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='transcription_audio/'),
        ),
    ]
