# Generated by Django 5.1.4 on 2026-04-19 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Nexcribe Lucky Wheel', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'wheel_configs',
            },
        ),
        migrations.CreateModel(
            name='WheelSlice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
                ('reward_type', models.CharField(choices=[('CASH', 'Cash Credit'), ('SPINS', 'Bonus Spins'), ('NONE', 'No Reward (Try Again)')], default='CASH', max_length=10)),
                ('reward_value_kes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reward_spins', models.PositiveIntegerField(default=0)),
                ('probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('color_hex', models.CharField(default='#0a7c5c', max_length=7)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slices', to='wheel.wheelconfig')),
            ],
            options={
                'db_table': 'wheel_slices',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SpinResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_type', models.CharField(max_length=10)),
                ('reward_kes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reward_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bonus_spins', models.PositiveIntegerField(default=0)),
                ('transaction_code', models.CharField(blank=True, max_length=20)),
                ('credited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_results', to=settings.AUTH_USER_MODEL)),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel.wheelconfig')),
                ('slice_won', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wheel.wheelslice')),
            ],
            options={
                'db_table': 'spin_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
