# Generated by Django 5.1.4 on 2026-04-19 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(choices=[('quiz', 'Quiz'), ('trivia', 'Trivia'), ('word_puzzle', 'Word Puzzle'), ('slots', 'Slots Machine'), ('number_match', 'Number Match'), ('memory', 'Memory Game'), ('speed_type', 'Speed Typing'), ('vip_challenge', 'VIP Challenge')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('min_plan_level', models.PositiveSmallIntegerField(default=1)),
                ('reward_per_win_kes', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('reward_per_win_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'games',
                'ordering': ['min_plan_level'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=15)),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('reward_earned_kes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reward_earned_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reward_credited', models.BooleanField(default=False)),
                ('transaction_code', models.CharField(blank=True, max_length=20)),
                ('session_token', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('question_ids', models.JSONField(default=list)),
                ('correct_answers', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'game_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'quiz_questions',
            },
        ),
        migrations.CreateModel(
            name='GameLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('sessions_played', models.PositiveIntegerField(default=0)),
                ('total_earned_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='games.game')),
            ],
            options={
                'db_table': 'game_leaderboard',
                'ordering': ['rank'],
            },
        ),
    ]
