# Generated by Django 5.1.4 on 2026-04-29 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_initial'),
        ('plans', '0003_add_weekly_reset_to_userplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='amount_usd',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commission',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='plan_price_kes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PAID', max_length=10),
        ),
    ]
