# Generated by Django 5.1.4 on 2026-04-19 05:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_code', models.CharField(max_length=20, unique=True)),
                ('wallet_type', models.CharField(choices=[('ACCOUNT', 'Account Wallet'), ('YIELDS', 'Yields Wallet')], max_length=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('CARD', 'Card')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('account_details', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing')], default='PENDING', max_length=15)),
                ('admin_note', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'withdrawal_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
