# Generated by Django 5.1.4 on 2026-05-01 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_withdrawalrequest_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPaymentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(help_text='M-Pesa phone number (e.g., 0750518501)', max_length=20, unique=True)),
                ('account_name', models.CharField(help_text='Account name (e.g., RAHAB)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is currently active')),
            ],
            options={
                'verbose_name': 'M-Pesa Payment Detail',
                'verbose_name_plural': 'M-Pesa Payment Details',
                'db_table': 'mpesa_payment_details',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
