# Generated by Django 5.1.4 on 2026-04-26 11:35

import apps.users.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('WRITING', 'Writing Task'), ('TRANSCRIPTION', 'Transcription Task'), ('GAME', 'Game Reward'), ('WHEEL', 'Wheel Spin'), ('REFERRAL', 'Referral Commission'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit'), ('PLAN_PURCHASE', 'Plan Purchase'), ('CASHBACK', 'Cashback'), ('REFUND', 'Refund')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_type',
            field=models.CharField(choices=[('ACCOUNT', 'Account Wallet'), ('YIELDS', 'Yields Wallet'), ('DEPOSIT', 'Deposit Wallet'), ('CASHBACK', 'Cashback Wallet')], max_length=10),
        ),
        migrations.CreateModel(
            name='CashbackWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_earned_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cashback_wallets',
            },
        ),
        migrations.CreateModel(
            name='DepositWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_deposited_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_spent_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deposit_wallets',
            },
        ),
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(default=apps.users.models.generate_virtual_card_number, max_length=19)),
                ('expiry', models.CharField(default=apps.users.models.generate_card_expiry, max_length=5)),
                ('cvv', models.CharField(default=apps.users.models.generate_cvv, max_length=3)),
                ('card_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'virtual_cards',
            },
        ),
    ]
