# Generated by Django 5.1.4 on 2026-04-19 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('WRITING', 'Writing'), ('TRANSCRIPTION', 'Transcription'), ('GAMING', 'Gaming')], max_length=20)),
                ('level', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('writing_tasks_per_month', models.PositiveIntegerField(default=0)),
                ('writing_max_pay_per_task_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('writing_revisions_per_task', models.PositiveIntegerField(default=0)),
                ('writing_priority_queue', models.BooleanField(default=False)),
                ('writing_direct_assignments', models.BooleanField(default=False)),
                ('transcription_tasks_per_month', models.PositiveIntegerField(default=0)),
                ('transcription_max_audio_minutes', models.PositiveIntegerField(default=0)),
                ('transcription_max_pay_per_task_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transcription_difficulty_access', models.CharField(choices=[('BASIC', 'Basic'), ('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('ALL', 'All')], default='BASIC', max_length=20)),
                ('transcription_priority_queue', models.BooleanField(default=False)),
                ('gaming_plays_per_day', models.PositiveIntegerField(default=0)),
                ('gaming_max_win_per_day_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gaming_wheel_spins_per_day', models.PositiveIntegerField(default=0)),
                ('gaming_games_unlocked', models.JSONField(default=list)),
                ('gaming_leaderboard_bonus', models.BooleanField(default=False)),
                ('gaming_tournament_access', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('features_list', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['category', 'level'],
                'unique_together': {('category', 'level')},
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_code', models.CharField(blank=True, max_length=20)),
                ('writing_tasks_used', models.PositiveIntegerField(default=0)),
                ('transcription_tasks_used', models.PositiveIntegerField(default=0)),
                ('gaming_plays_today', models.PositiveIntegerField(default=0)),
                ('wheel_spins_today', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_plans', to='plans.plan')),
            ],
            options={
                'db_table': 'user_plans',
            },
        ),
    ]
