# Generated by Django 5.1.4 on 2026-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='transcription_max_audio_minutes',
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
