# Generated by Django 5.1.4 on 2026-04-26 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('COMMISSION', 'Commission Earned'), ('REFERRAL', 'New Referral'), ('PLAN_PURCHASE', 'Plan Purchased'), ('WITHDRAWAL', 'Withdrawal Update'), ('DEPOSIT', 'Deposit Update'), ('TASK_APPROVED', 'Task Approved'), ('TASK_REJECTED', 'Task Rejected'), ('TASK_ASSIGNED', 'Task Assigned'), ('GAME_REWARD', 'Game Reward'), ('SPIN_WIN', 'Wheel Spin Win'), ('SYSTEM', 'System Message'), ('ADMIN_REMARK', 'Admin Remark')], max_length=20),
        ),
    ]
